apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    system.querying: "true"
data:
  config.yaml: |
    config:
      PORT: "{{ .Values.data.port }}"
      ROUTES_PREFIX: "{{ .Values.data.routes_prefix }}"
      API_RESPONSE_VERSION: "{{ .Values.data.api_response_version }}"
      MAX_PAYLOAD_SIZE_IN_KB: {{ .Values.data.max_payload_size_in_kb }}
      GOMAXPROCS: {{ .Values.data.gomaxprocs }}
      ERROR_CODE: "{{ .Values.data.error_code }}"
      READ_BUFFER_SIZE: {{ .Values.data.read_buffer_size }}
      ENV: "{{ .Values.data.env }}"
      LOG_LEVEL: "{{ .Values.data.log_level }}"
      processConfig:
        log_transactions: {{ .Values.data.processConfig.log_transactions }}
        developer_config:
          capture_txn: {{ .Values.data.processConfig.developer_config.capture_txn }}
      store:
        db:
          datastore_path: "{{ .Values.data.store.db.datastore_path }}"
      sla:
        sla_api_url: "{{ .Values.data.sla.sla_api_url }}"
        token_generation_base_url: "{{ .Values.data.sla.token_generation_base_url }}"
        aa_webhook_url: "{{ .Values.data.sla.aa_webhook_url }}"
        jws_signing_enabled: {{ .Values.data.sla.jws_signing_enabled }}
        jws_private_key_path: "{{ .Values.data.sla.jws_private_key_path }}"
        log_percentile_values: {{ .Values.data.sla.log_percentile_values }}
      entityConfig:
        credentials: "{{ .Values.data.entityConfig.credentials }}"
      tls:
        https_enabled: {{ .Values.data.tls.https_enabled }}
        cert_file: "{{ .Values.data.tls.cert_file }}"
        key_file: "{{ .Values.data.tls.key_file }}"
