{{- if and .Values.global .Values.global.enable_nginx_kong }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.ingress.api_name }}-kong"
  namespace: "{{ .Values.ingress.namespace }}"
  annotations:
    konghq.com/path: ~^/sna/v1/(.*)
    konghq.com/rewrite: /sna/v1/$1
    konghq.com/strip-path: "true"
    {{- if and .Values.data.tls.https_enabled .Values.data.tls.secretName }}
    konghq.com/backend-protocol: https
    {{- end }}
spec:
  ingressClassName: "{{ .Values.global.kong_ingress_class }}"
  tls:
    - hosts:
      - "{{ .Values.ingress.api_host }}"
      secretName: "{{ .Values.ingress.api_secret_name }}-kong"
  rules:
    - host: "{{ .Values.ingress.api_host }}"
      http:
        paths:
        - backend:
            service:
              name: "{{ .Chart.Name }}"
              port:
                name: {{ if and .Values.data.tls.https_enabled .Values.data.tls.secretName }}https{{ else }}http{{ end }}
          path: /sna/v1/(.*)
          pathType: Prefix

{{- end }}
