{{- if and .Values.global .Values.global.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-login
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.global.secret }}
{{- end }}
